/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller_qlks.DichVu;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dichvuControctor;

/**
 *
 * @author Phuc Map
 */
public class formQL_DichVu extends javax.swing.JFrame 
{

    private ArrayList<dichvuControctor> listDV = new ArrayList<>();
    public static DichVu dv;
    private boolean checkSearch = false;
    private Object ex;
    
    /**
     * Creates new form JFR_DichVu
     */
    public formQL_DichVu() 
    {
        initComponents();
        dv = new DichVu();
        listDV = dv.getListDV();
        loadTableDV(listDV);
        soluongDv();
    }
    
    public static void soluongDv() {
        int number = dv.getNumberDV();
        Txt_SoLuongDv.setText("Tổng sô dịch vụ : " + number);
    }
    
    public void loadTableDV(ArrayList<dichvuControctor> listDV) 
    {
        DefaultTableModel model = (DefaultTableModel) Tb_DichVu.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listDV.size(); i++) {
            model.addRow(new Object[]
            {
                listDV.get(i).getId(),
                listDV.get(i).getTendv(),
                listDV.get(i).getGiadv(),
                
            });
        }
        Tb_DichVu.setModel(model);
    }
    
    
    public void timDV() 
    {
        String key = TF_Search.getText();
        
        listDV = dv.searchDV(key);
        if (listDV.size() != 0) 
        {
            loadTableDV(listDV);
            checkSearch = true;
        } 
        else 
        {
            JOptionPane.showMessageDialog(this, "Không có kết quả phù hợp", "Tìm kiếm", JOptionPane.INFORMATION_MESSAGE);            
            checkSearch = false;
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_DichVu = new javax.swing.JTable();
        Bt_XemCT = new javax.swing.JButton();
        Bt_Them = new javax.swing.JButton();
        Bt_Sua = new javax.swing.JButton();
        Bt_Xoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txt_SoLuongDv = new javax.swing.JTextArea();
        TF_Search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Bt_Tim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tb_DichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Giá tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_DichVu.setColumnSelectionAllowed(true);
        Tb_DichVu.setRowHeight(25);
        Tb_DichVu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Tb_DichVu);
        Tb_DichVu.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Tb_DichVu.getColumnModel().getColumnCount() > 0) {
            Tb_DichVu.getColumnModel().getColumn(0).setResizable(false);
            Tb_DichVu.getColumnModel().getColumn(1).setResizable(false);
            Tb_DichVu.getColumnModel().getColumn(2).setResizable(false);
        }

        Bt_XemCT.setBackground(new java.awt.Color(0, 153, 255));
        Bt_XemCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_XemCT.setForeground(new java.awt.Color(255, 255, 255));
        Bt_XemCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view_white.png"))); // NOI18N
        Bt_XemCT.setText("Xem chi tiết");
        Bt_XemCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bt_XemCT.setIconTextGap(15);
        Bt_XemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_XemCTActionPerformed(evt);
            }
        });

        Bt_Them.setBackground(new java.awt.Color(0, 153, 255));
        Bt_Them.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_Them.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_white.png"))); // NOI18N
        Bt_Them.setText("Thêm");
        Bt_Them.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bt_Them.setIconTextGap(15);
        Bt_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ThemActionPerformed(evt);
            }
        });

        Bt_Sua.setBackground(new java.awt.Color(0, 153, 255));
        Bt_Sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_Sua.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_white.png"))); // NOI18N
        Bt_Sua.setText("Chỉnh sửa");
        Bt_Sua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bt_Sua.setIconTextGap(15);
        Bt_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SuaActionPerformed(evt);
            }
        });

        Bt_Xoa.setBackground(new java.awt.Color(0, 153, 255));
        Bt_Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_white.png"))); // NOI18N
        Bt_Xoa.setText("Xóa");
        Bt_Xoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bt_Xoa.setIconTextGap(15);
        Bt_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_XoaActionPerformed(evt);
            }
        });

        Txt_SoLuongDv.setEditable(false);
        Txt_SoLuongDv.setColumns(20);
        Txt_SoLuongDv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_SoLuongDv.setLineWrap(true);
        Txt_SoLuongDv.setRows(3);
        Txt_SoLuongDv.setAutoscrolls(false);
        jScrollPane2.setViewportView(Txt_SoLuongDv);

        TF_Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TF_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_SearchKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        Bt_Tim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_Tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_black.png"))); // NOI18N
        Bt_Tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_TimMouseClicked(evt);
            }
        });
        Bt_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bt_Them, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Sua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Bt_XemCT, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Bt_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bt_Tim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TF_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bt_XemCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_XemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_XemCTActionPerformed
        // TODO add your handling code here:
        
        int row = Tb_DichVu.getSelectedRow();
        if (row != -1) 
        {
            dichvuControctor DvControctor = new dichvuControctor(); 
            if (checkSearch == true)
            {
                DvControctor = listDV.get(row);
            }
            else
            {
                listDV = dv.getListDV();
                DvControctor = listDV.get(row);
            }
            formAdd_DV add_DV = new formAdd_DV(this, DvControctor, 1);
            add_DV.setVisible(true);
            add_DV.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            add_DV.setLocationRelativeTo(null);
           
        } 
        else 
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE);//, icon.iconError());
        }
        
    }//GEN-LAST:event_Bt_XemCTActionPerformed

    private void Bt_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ThemActionPerformed
        // TODO add your handling code here:
        formAdd_DV add_DV = new formAdd_DV(this);
        add_DV.setVisible(true);
    }//GEN-LAST:event_Bt_ThemActionPerformed

    private void Bt_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SuaActionPerformed
        // TODO add your handling code here:
        
        int row = Tb_DichVu.getSelectedRow();
        if (row != -1) 
        
        {
            dichvuControctor DvControctor = new dichvuControctor();
            if (checkSearch == true) 
            {
                DvControctor = listDV.get(row);
            } 
            else 
            {
                listDV = dv.getListDV();
                DvControctor = listDV.get(row);
            }
            
            formAdd_DV add_DV = new formAdd_DV(this, DvControctor, 2);
            add_DV.setVisible(true);
            add_DV.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            add_DV.setLocationRelativeTo(null);
        } 
        
        else 
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE);//, icon.iconError());
        }
        
    }//GEN-LAST:event_Bt_SuaActionPerformed

    private void Bt_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_XoaActionPerformed
        // TODO add your handling code here:
        
      int row = Tb_DichVu.getSelectedRow();
        if (row != -1) 
        {
            String iddv = Tb_DichVu.getValueAt(row, 0).toString();
            int output = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhân viên " + iddv + "?", "Xóa nhân viên", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);//, icon.iconDelete());
            if (output == JOptionPane.YES_OPTION) 
           
            {
                if (dv.deleteDv(iddv)) 
                {
                    JOptionPane.showMessageDialog(this, "Xóa thành công", "Xóa", JOptionPane.INFORMATION_MESSAGE);
                    loadTableDV(dv.getListDV());
                  
                } 
                else 
                {
                    JOptionPane.showMessageDialog(this, "Chưa xóa được", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }

        } 
        else 
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_Bt_XoaActionPerformed

    private void Bt_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_TimActionPerformed
        
    }//GEN-LAST:event_Bt_TimActionPerformed

    private void TF_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_SearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try {
                String key = TF_Search.getText();
                loadTableDV(listDV);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_TF_SearchKeyPressed

    private void Bt_TimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_TimMouseClicked
        // TODO add your handling code here:
       if (checkSearch == false) 
        {
            timDV();
        } 
       else 
       {
            listDV = dv.getListDV();
            loadTableDV(listDV);
            
            checkSearch = false;
        }
    }//GEN-LAST:event_Bt_TimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formQL_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formQL_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formQL_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formQL_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formQL_DichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Sua;
    private javax.swing.JButton Bt_Them;
    private javax.swing.JButton Bt_Tim;
    private javax.swing.JButton Bt_XemCT;
    private javax.swing.JButton Bt_Xoa;
    private javax.swing.JTextField TF_Search;
    private javax.swing.JTable Tb_DichVu;
    public static javax.swing.JTextArea Txt_SoLuongDv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables



   


}
